yitai:
  datasource:
    url: jdbc:mysql://rm-0jlecmy5dzw5m5lveyo.mysql.rds.aliyuncs.com:3306/supply_chain_test?characterEncoding=utf-8
    username: yitai
    password: Yitai@888
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 8.130.8.127
    port: 6379
    database: 0
    password: yitai
qingniu:
  accesskey: 3iOb1ZZZ24XqeFn9R_yQYYep-IhQOYshyVEI2O73
  secretkey: QE9Lc9FP926-XlEqECstUCTfYtlhrBYUIyzZTuDU